/*
 * This file is part of the openHiTLS project.
 *
 * openHiTLS is licensed under the Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *     http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

#ifndef PQCP_TYPES_H
#define PQCP_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

#include "internal/mceliece_params.h"

#define CRYPT_PARAM_SCLOUDPLUS_BASE 900
#define CRYPT_PARAM_SCLOUDPLUS_PUBKEY (CRYPT_PARAM_SCLOUDPLUS_BASE + 1)
#define CRYPT_PARAM_SCLOUDPLUS_PRVKEY (CRYPT_PARAM_SCLOUDPLUS_BASE + 2)
#define CRYPT_PARAM_FRODOKEM_BASE 1000
#define CRYPT_PARAM_FRODOKEM_PUBKEY (CRYPT_PARAM_FRODOKEM_BASE + 1)
#define CRYPT_PARAM_FRODOKEM_PRVKEY (CRYPT_PARAM_FRODOKEM_BASE + 2)
#define CRYPT_PARAM_MCELIECE_BASE 1100
#define CRYPT_PARAM_MCELIECE_PUBKEY (CRYPT_PARAM_MCELIECE_BASE + 1)
#define CRYPT_PARAM_MCELIECE_PRVKEY (CRYPT_PARAM_MCELIECE_BASE + 2)
#define CRYPT_PARAM_POLAR_LAC_PRVKEY_BASE 1200
#define CRYPT_PARAM_POLAR_LAC_PRVKEY (CRYPT_PARAM_POLAR_LAC_PRVKEY_BASE + 1)
#define CRYPT_PARAM_POLAR_LAC_PUBKEY (CRYPT_PARAM_POLAR_LAC_PRVKEY_BASE + 2)
typedef enum
{
    PQCP_SCLOUDPLUS_KEY_BITS,
    PQCP_SCLOUDPLUS_GET_PARA,
    PQCP_SCLOUDPLUS_GET_CIPHERLEN,
    PQCP_SCLOUDPLUS_GET_SECBITS,
    PQCP_FRODOKEM_ALG_PARAMS,
    PQCP_FRODOKEM_GET_PARA,
    PQCP_FRODOKEM_GET_CIPHERLEN,
    PQCP_FRODOKEM_GET_SECBITS,
    PQCP_FRODOKEM_SET_PARAMS_BY_ID,
    PQCP_MCELIECE_ALG_PARAMS,
    PQCP_MCELIECE_GET_PARA,
    PQCP_MCELIECE_GET_CIPHERLEN,
    PQCP_MCELIECE_GET_SECBITS,
    PQCP_POLAR_LAC_SET_PARAMS_BY_ID,
    PQCP_POLAR_LAC_GET_CIPHER_LEN,
    PQCP_POLAR_LAC_GET_PRVKEY_LEN,
    PQCP_POLAR_LAC_GET_PUBKEY_LEN,
} PQCP_PKEY_CTRL_TYPE;

typedef enum
{
    PQCP_MCELIECE_ALG_ID_6688128 = PQC_ALG_ID_MCELIECE_6688128,
    PQCP_MCELIECE_ALG_ID_6688128_F = PQC_ALG_ID_MCELIECE_6688128_F,
    PQCP_MCELIECE_ALG_ID_6688128_PC = PQC_ALG_ID_MCELIECE_6688128_PC,
    PQCP_MCELIECE_ALG_ID_6688128_PCF = PQC_ALG_ID_MCELIECE_6688128_PCF,

    PQCP_MCELIECE_ALG_ID_6960119 = PQC_ALG_ID_MCELIECE_6960119,
    PQCP_MCELIECE_ALG_ID_6960119_F = PQC_ALG_ID_MCELIECE_6960119_F,
    PQCP_MCELIECE_ALG_ID_6960119_PC = PQC_ALG_ID_MCELIECE_6960119_PC,
    PQCP_MCELIECE_ALG_ID_6960119_PCF = PQC_ALG_ID_MCELIECE_6960119_PCF,

    PQCP_MCELIECE_ALG_ID_8192128 = PQC_ALG_ID_MCELIECE_8192128,
    PQCP_MCELIECE_ALG_ID_8192128_F = PQC_ALG_ID_MCELIECE_8192128_F,
    PQCP_MCELIECE_ALG_ID_8192128_PC = PQC_ALG_ID_MCELIECE_8192128_PC,
    PQCP_MCELIECE_ALG_ID_8192128_PCF = PQC_ALG_ID_MCELIECE_8192128_PCF

} PQCP_MCELIECE_ALG_ID;

typedef enum {
    PQCP_POLAR_LAC_LIGHT,
    PQCP_POLAR_LAC_128,
    PQCP_POLAR_LAC_256,
} PQCP_POLAR_LAC_ALG_ID;

#ifdef __cplusplus
}
#endif

#endif /* PQCP_TYPES_H */
