/*
 * This file is part of the openHiTLS project.
 *
 * openHiTLS is licensed under the Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *
 *     http://license.coscl.org.cn/MulanPSL2
 *
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

#ifndef PQCP_TYPES_H
#define PQCP_TYPES_H

#ifdef __cplusplus
extern "C" {
#endif

#define PQCP_PARAM_BASE 5000
#define PQCP_PARAM_SCLOUDPLUS_BASE (PQCP_PARAM_BASE + 100)
#define PQCP_PARAM_SCLOUDPLUS_PUBKEY (PQCP_PARAM_SCLOUDPLUS_BASE + 1)
#define PQCP_PARAM_SCLOUDPLUS_PRVKEY (PQCP_PARAM_SCLOUDPLUS_BASE + 2)

#define PQCP_PARAM_POLAR_LAC_BASE (PQCP_PARAM_BASE + 200)
#define PQCP_PARAM_POLAR_LAC_PRVKEY (PQCP_PARAM_POLAR_LAC_BASE + 1)
#define PQCP_PARAM_POLAR_LAC_PUBKEY (PQCP_PARAM_POLAR_LAC_BASE + 2)

#define PQCP_PARAM_COMPOSITE_SIGN_BASE (PQCP_PARAM_BASE + 300)
#define PQCP_PARAM_COMPOSITE_PUBKEY (PQCP_PARAM_COMPOSITE_SIGN_BASE + 1)
#define PQCP_PARAM_COMPOSITE_PRVKEY (PQCP_PARAM_COMPOSITE_SIGN_BASE + 2)
typedef enum
{
    PQCP_SCLOUDPLUS_GET_PARA = 2000,
    PQCP_SCLOUDPLUS_GET_SECBITS,

    PQCP_CTRL_HYBRID_GET_KEM_PUBKEY,
    PQCP_CTRL_HYBRID_GET_KEM_PRVKEY,
    PQCP_CTRL_HYBRID_GET_PKEY_PUBKEY,
    PQCP_CTRL_HYBRID_GET_PKEY_PRVKEY,
    PQCP_CTRL_HYBRID_SET_KEM_PUBKEY,
    PQCP_CTRL_HYBRID_SET_KEM_PRVKEY,
    PQCP_CTRL_HYBRID_SET_PKEY_PUBKEY,
    PQCP_CTRL_HYBRID_SET_PKEY_PRVKEY,
    PQCP_CTRL_HYBRID_GET_LABEL,
    PQCP_CTRL_HYBRID_GET_PQC_PUBKEY_LEN,
    PQCP_CTRL_HYBRID_GET_TRAD_PUBKEY_LEN,
    PQCP_CTRL_HYBRID_GET_PQC_PRVKEY_LEN,
    PQCP_CTRL_HYBRID_GET_TRAD_PRVKEY_LEN,
    PQCP_CTRL_HYBRID_GET_PQC_CIPHER_LEN,
    PQCP_CTRL_HYBRID_GET_TRAD_CIPHER_LEN,
    PQCP_CTRL_HYBRID_GET_PQC_SIGNLEN,
    PQCP_CTRL_HYBRID_GET_TRAD_SIGNLEN,
} PQCP_PKEY_CTRL_TYPE;

typedef enum {
    PQCP_SCLOUDPLUS_128 = 6000,
    PQCP_SCLOUDPLUS_192,
    PQCP_SCLOUDPLUS_256,

    PQCP_POLAR_LAC_LIGHT,
    PQCP_POLAR_LAC_128,
    PQCP_POLAR_LAC_256,

    PQCP_COMPOSITE_MLDSA44_SM2,
    PQCP_COMPOSITE_MLDSA65_SM2,
    PQCP_COMPOSITE_MLDSA87_SM2
} PQCP_ALG_ID;

#ifdef __cplusplus
}
#endif

#endif /* PQCP_TYPES_H */
